### ISSUE TITLE
Crashes Vanilla when I attempt to open this plugin

### ISSUE THREAD

**Issue by mainmachine** [vanilla-music/vanilla-music-metadata-fetch#1]
I'm on a Moto G5S with Oreo, not rooted nothing crazy, developer options enabled. I launch Vanilla music, go to a song > context menu > plugins > metadata fetch and a popup window opens, progress wheel spins for a few seconds then and error message appears: "Vanilla Metadata Fetch has failed"

**Comment by Kaned1as** [comment]
I believe this is fixed now by https://github.com/vanilla-music/vanilla-music-metadata-fetch/commit/ae2a2fb87f5cf13a825298965b43ab9c55f68e31. Wait for an update.
In case it's not, feel free to comment here, I'll reopen it.

**Comment by mainmachine** [comment]
Got the update via Fdroid yesterday, and now it works as expected. Thank you very much! :)
