### ISSUE TITLE
Error while writing metadata to audio file 

### ISSUE THREAD

**Issue by jhoc2000** [vanilla-music/vanilla-music-metadata-fetch#5]
Metadata fetch seems to find the song's metadata as it presents it in a popup window but gets an error when trying to write to the audio file. The error looks something like:

"Error while working with audio file /storage/9C33-6BBD/Music/....." etcetera. 

It may have something to do with the music file being on an SDCard and not the internal memory or permissions to write to that file/file system. 

How can I overcome this problem?

**Comment by Kaned1as** [comment]
Most probably yes, external storage support 

* What's the file format? 
* Did you grant the access to the external storage to the app?
* If no, did you see a dialog requesting access to the external storage?

**Comment by jhoc2000** [comment]
Please see answers online below. 

On 25 April 2020 8:25:17 pm AEST, Kanedias <notifications@github.com> wrote:
>Most probably yes, external storage support 
>
>* What's the file format? 

m4a

>* Did you grant the access to the external storage to the app?

No. 

>* If no, did you see a dialog requesting access to the external
>storage?

No. 

I hope that this helps.

**Comment by Kaned1as** [comment]
Can you share this file? I have a suspicion that it has something to do with how jaudiotagger works with m4a.

**Comment by jhoc2000** [comment]
I hope so.

Please find it attached.

**Comment by Kaned1as** [comment]
You replied via mail, GitHub doesn't attach it like this

**Comment by jhoc2000** [comment]
1. Assault & Battery Part I.txt

I think this is the file. I had to rename it to a ,txt file to be able to paste it into GitHub. Please rename it to a .m4a file before trying to play it.

**Comment by jhoc2000** [comment]
Bother! I didn't want to close it so I'll have to open it again.

**Comment by jhoc2000** [comment]
1. Assault & Battery Part I.m4a

Apparently I can post a .m4a file?

**Comment by jhoc2000** [comment]
[1. Assault & Battery Part I.txt](https://github.com/vanilla-music/vanilla-music-metadata-fetch/files/4591051/1.Assault.Battery.Part.I.txt)

Third time lucky. Cut and paste doesn't work on GitHub or this platform. Hopefully it'll work now. Don't forget to rename the file to a .m4a extension.

**Comment by Kaned1as** [comment]
@jhoc2000 try with latest Tag Editor plugin from Google Play. If you're using F-Doid you'll have to wait, their updates are a bit lagging, around 1-2 days.

**Comment by jhoc2000** [comment]
I updated Tag Editor to version 1.4.7.
I was asked to allow it to access files etcetera, which I granted. (I still can't edit the Title, Artist nor Album but that's another issue) I selected the "OK" option and an: 

"SAF exchange error:Cannot make changes.... " error showed up in a temporary window as follows:

![Screenshot_20200511-104324_Vanilla_Music](https://user-images.githubusercontent.com/16982707/81514871-b6c3dc00-9374-11ea-9d59-b19dfc101905.png)

**Comment by jhoc2000** [comment]
After uninstalling Metadata Fetch and installing version 1.0.4 I then used Metada Fetch to get the metadata for music that was playing and when I chose to write the metadata the music stopped and the original error showed again. That is, "Error while working with audio file /storage/9C33-6BBD/Music/.....".

**Comment by jhoc2000** [comment]
I just noticed that the directory /storage/emulated/0/Android/data/com.kanedias.vanilla.audiotag/cache/ doesn't exist on my phone. Does this help?
